#!/bin/bash

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# battery_lite                                                          #
#  Copyright (C) 2012 eu-slack <eu-slack [at] mail [dot] com>           #
#                                                                       #
#  This program is free software: you can redistribute it and/or modify #
#  it under the terms of the GNU General Public License as published by #
#  the Free Software Foundation, either version 3 of the License, or    #
#  (at your option) any later version.                                  #
#                                                                       #
#  This program is distributed in the hope that it will be useful,      #
#  but WITHOUT ANY WARRANTY; without even the implied warranty of	    #
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the	        #
#  GNU General Public License for more details.                         #
#                                                                       #
#  You should have received a copy of the GNU General Public License    #
#  along with this program. If not, see http://www.gnu.org/licenses/    #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #	#

SOURCE="/sys/class/power_supply/BAT0/"

if [ -d $SOURCE ]
then
  STATUS=`cat "$SOURCE"status`
  FULL=`cat "$SOURCE"charge_full_design`
  NOW=`cat "$SOURCE"charge_now`

  FULL=$((FULL / 100))
  PERCENT=$((NOW / FULL))

  echo $PERCENT% $STATUS
else
  echo Not present
fi

exit 0
